// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hsgp_approx_sample
arma::mat hsgp_approx_sample(const arma::mat& dyn_trans_mat, const arma::vec& hyperparameters, const Rcpp::List& kernel, const arma::mat& X, const arma::mat& basis_fun_index, const arma::vec& boundry_factor);
RcppExport SEXP _gpssmR_hsgp_approx_sample(SEXP dyn_trans_matSEXP, SEXP hyperparametersSEXP, SEXP kernelSEXP, SEXP XSEXP, SEXP basis_fun_indexSEXP, SEXP boundry_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dyn_trans_mat(dyn_trans_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hyperparameters(hyperparametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type basis_fun_index(basis_fun_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundry_factor(boundry_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(hsgp_approx_sample(dyn_trans_mat, hyperparameters, kernel, X, basis_fun_index, boundry_factor));
    return rcpp_result_gen;
END_RCPP
}
// gpssm_sample
arma::mat gpssm_sample(const arma::uword& n_iter, const arma::uword& n_warm_up, const arma::uword& n_thin, const arma::uword& n_particles, const arma::uword& n_time, const arma::uword& d_lat, const arma::uword& d_obs, arma::mat y, arma::mat x, const arma::mat& covariate_dyn, const arma::mat& covariate_meas, const arma::vec& t0_mean, const arma::mat& t0_cov, const arma::mat& basis_fun_index, const arma::vec& boundry_factor, const Rcpp::Function& dprior, const Rcpp::Function& rprior, const Rcpp::List& kernel, arma::mat dyn_design_mat_mean, const arma::mat dyn_covar_mat_mean, const arma::mat dyn_covar_mat_col_cov, const Rcpp::List& dyn_cov_list, const arma::mat meas_design_mat_const, const arma::vec meas_design_mat_mean_alt, const arma::mat meas_design_mat_cov_alt, const arma::mat meas_covar_mat_const, const arma::vec meas_covar_mat_mean_alt, const arma::mat meas_covar_mat_cov_alt, const Rcpp::List& meas_cov_list, const arma::uword& mh_rep, const arma::uword& pg_rep, const arma::uword mh_adapt_start, bool exact, bool post_pred, bool disp_prog);
RcppExport SEXP _gpssmR_gpssm_sample(SEXP n_iterSEXP, SEXP n_warm_upSEXP, SEXP n_thinSEXP, SEXP n_particlesSEXP, SEXP n_timeSEXP, SEXP d_latSEXP, SEXP d_obsSEXP, SEXP ySEXP, SEXP xSEXP, SEXP covariate_dynSEXP, SEXP covariate_measSEXP, SEXP t0_meanSEXP, SEXP t0_covSEXP, SEXP basis_fun_indexSEXP, SEXP boundry_factorSEXP, SEXP dpriorSEXP, SEXP rpriorSEXP, SEXP kernelSEXP, SEXP dyn_design_mat_meanSEXP, SEXP dyn_covar_mat_meanSEXP, SEXP dyn_covar_mat_col_covSEXP, SEXP dyn_cov_listSEXP, SEXP meas_design_mat_constSEXP, SEXP meas_design_mat_mean_altSEXP, SEXP meas_design_mat_cov_altSEXP, SEXP meas_covar_mat_constSEXP, SEXP meas_covar_mat_mean_altSEXP, SEXP meas_covar_mat_cov_altSEXP, SEXP meas_cov_listSEXP, SEXP mh_repSEXP, SEXP pg_repSEXP, SEXP mh_adapt_startSEXP, SEXP exactSEXP, SEXP post_predSEXP, SEXP disp_progSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uword& >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_warm_up(n_warm_upSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_particles(n_particlesSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type d_lat(d_latSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariate_dyn(covariate_dynSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariate_meas(covariate_measSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t0_mean(t0_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type t0_cov(t0_covSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type basis_fun_index(basis_fun_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundry_factor(boundry_factorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type dprior(dpriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type rprior(rpriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dyn_design_mat_mean(dyn_design_mat_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type dyn_covar_mat_mean(dyn_covar_mat_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type dyn_covar_mat_col_cov(dyn_covar_mat_col_covSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dyn_cov_list(dyn_cov_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_design_mat_const(meas_design_mat_constSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type meas_design_mat_mean_alt(meas_design_mat_mean_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_design_mat_cov_alt(meas_design_mat_cov_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_covar_mat_const(meas_covar_mat_constSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type meas_covar_mat_mean_alt(meas_covar_mat_mean_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_covar_mat_cov_alt(meas_covar_mat_cov_altSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type meas_cov_list(meas_cov_listSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type mh_rep(mh_repSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type pg_rep(pg_repSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type mh_adapt_start(mh_adapt_startSEXP);
    Rcpp::traits::input_parameter< bool >::type exact(exactSEXP);
    Rcpp::traits::input_parameter< bool >::type post_pred(post_predSEXP);
    Rcpp::traits::input_parameter< bool >::type disp_prog(disp_progSEXP);
    rcpp_result_gen = Rcpp::wrap(gpssm_sample(n_iter, n_warm_up, n_thin, n_particles, n_time, d_lat, d_obs, y, x, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, dprior, rprior, kernel, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_list, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_list, mh_rep, pg_rep, mh_adapt_start, exact, post_pred, disp_prog));
    return rcpp_result_gen;
END_RCPP
}
// gpssm_prior_sample
arma::mat gpssm_prior_sample(const arma::uword& n_iter, const arma::uword& n_time, const arma::uword& d_lat, const arma::uword& d_obs, const arma::mat& covariate_dyn, const arma::mat& covariate_meas, const arma::vec& t0_mean, const arma::mat& t0_cov, const arma::mat& basis_fun_index, const arma::vec& boundry_factor, const Rcpp::Function& rprior, const Rcpp::List& kernel, arma::mat dyn_design_mat_mean, const arma::mat dyn_covar_mat_mean, const arma::mat dyn_covar_mat_col_cov, const Rcpp::List& dyn_cov_list, const arma::mat meas_design_mat_const, const arma::vec meas_design_mat_mean_alt, const arma::mat meas_design_mat_cov_alt, const arma::mat meas_covar_mat_const, const arma::vec meas_covar_mat_mean_alt, const arma::mat meas_covar_mat_cov_alt, const Rcpp::List& meas_cov_list, const arma::mat& y, bool exact, bool pred, bool disp_prog);
RcppExport SEXP _gpssmR_gpssm_prior_sample(SEXP n_iterSEXP, SEXP n_timeSEXP, SEXP d_latSEXP, SEXP d_obsSEXP, SEXP covariate_dynSEXP, SEXP covariate_measSEXP, SEXP t0_meanSEXP, SEXP t0_covSEXP, SEXP basis_fun_indexSEXP, SEXP boundry_factorSEXP, SEXP rpriorSEXP, SEXP kernelSEXP, SEXP dyn_design_mat_meanSEXP, SEXP dyn_covar_mat_meanSEXP, SEXP dyn_covar_mat_col_covSEXP, SEXP dyn_cov_listSEXP, SEXP meas_design_mat_constSEXP, SEXP meas_design_mat_mean_altSEXP, SEXP meas_design_mat_cov_altSEXP, SEXP meas_covar_mat_constSEXP, SEXP meas_covar_mat_mean_altSEXP, SEXP meas_covar_mat_cov_altSEXP, SEXP meas_cov_listSEXP, SEXP ySEXP, SEXP exactSEXP, SEXP predSEXP, SEXP disp_progSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uword& >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type n_time(n_timeSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type d_lat(d_latSEXP);
    Rcpp::traits::input_parameter< const arma::uword& >::type d_obs(d_obsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariate_dyn(covariate_dynSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariate_meas(covariate_measSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type t0_mean(t0_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type t0_cov(t0_covSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type basis_fun_index(basis_fun_indexSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundry_factor(boundry_factorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type rprior(rpriorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dyn_design_mat_mean(dyn_design_mat_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type dyn_covar_mat_mean(dyn_covar_mat_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type dyn_covar_mat_col_cov(dyn_covar_mat_col_covSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dyn_cov_list(dyn_cov_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_design_mat_const(meas_design_mat_constSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type meas_design_mat_mean_alt(meas_design_mat_mean_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_design_mat_cov_alt(meas_design_mat_cov_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_covar_mat_const(meas_covar_mat_constSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type meas_covar_mat_mean_alt(meas_covar_mat_mean_altSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type meas_covar_mat_cov_alt(meas_covar_mat_cov_altSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type meas_cov_list(meas_cov_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type exact(exactSEXP);
    Rcpp::traits::input_parameter< bool >::type pred(predSEXP);
    Rcpp::traits::input_parameter< bool >::type disp_prog(disp_progSEXP);
    rcpp_result_gen = Rcpp::wrap(gpssm_prior_sample(n_iter, n_time, d_lat, d_obs, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, rprior, kernel, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_list, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_list, y, exact, pred, disp_prog));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_gpssmR_hsgp_approx_sample", (DL_FUNC) &_gpssmR_hsgp_approx_sample, 6},
    {"_gpssmR_gpssm_sample", (DL_FUNC) &_gpssmR_gpssm_sample, 35},
    {"_gpssmR_gpssm_prior_sample", (DL_FUNC) &_gpssmR_gpssm_prior_sample, 27},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpssmR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
