# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gpssm_sample <- function(n_iter, n_warm_up, n_thin, n_particles, n_time, d_lat, d_obs, y, x, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, dprior, rprior, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_df, dyn_cov_scale, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_df, meas_cov_scale, mh_rep, pg_rep, mh_adapt_start, exact = FALSE, post_pred = FALSE, disp_prog = TRUE) {
    .Call(`_gpssmR_gpssm_sample`, n_iter, n_warm_up, n_thin, n_particles, n_time, d_lat, d_obs, y, x, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, dprior, rprior, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_df, dyn_cov_scale, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_df, meas_cov_scale, mh_rep, pg_rep, mh_adapt_start, exact, post_pred, disp_prog)
}

gpssm_prior_sample <- function(n_iter, n_time, d_lat, d_obs, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, rprior, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_df, dyn_cov_scale, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_df, meas_cov_scale, y, exact = FALSE, pred = FALSE, disp_prog = TRUE) {
    .Call(`_gpssmR_gpssm_prior_sample`, n_iter, n_time, d_lat, d_obs, covariate_dyn, covariate_meas, t0_mean, t0_cov, basis_fun_index, boundry_factor, rprior, dyn_design_mat_mean, dyn_covar_mat_mean, dyn_covar_mat_col_cov, dyn_cov_df, dyn_cov_scale, meas_design_mat_const, meas_design_mat_mean_alt, meas_design_mat_cov_alt, meas_covar_mat_const, meas_covar_mat_mean_alt, meas_covar_mat_cov_alt, meas_cov_df, meas_cov_scale, y, exact, pred, disp_prog)
}

